# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo

commands:
  restore_repo:
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}-
            - v1-repo-

  restore_deps:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./yarn.lock" }}

jobs:
  checkout_code:
    executor: node
    steps:
      - restore_repo
      - checkout
      - save_cache:
          paths: .
          key: v1-repo-{{ .Branch }}-{{ .Revision }}

  install_deps:
    executor: node
    steps:
      - restore_repo
      - restore_deps
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "./yarn.lock" }}

  test:
    executor: node
    steps:
      - restore_repo
      - restore_deps
      - run: yarn install --frozen-lockfile
      - run: yarn run test

  publish:
    executor: node
    steps:
      - restore_repo
      - restore_deps
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2.1
  tests:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - install_deps:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install_deps
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
